version: '3.8' # Hoặc một phiên bản phù hợp khác

services:

  redis:
    image: redis:alpine # Sử dụng image Redis Alpine
    container_name: my_redis_container # Tên container (tùy chọn)
    ports:
      - "6379:6379" # Ánh xạ cổng 6379 của host tới cổng 6379 của container
    command: redis-server --appendonly yes # Bật chế độ AOF để persistence
    restart: unless-stopped # Tự động khởi động lại container trừ khi bạn chủ động dừng nó
