name: 'Deploy to Production'

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'seima-server'
  JAVA_VERSION: '21'
  DISTRIBUTION: 'temurin'

jobs:
  deploy:
    name: 'Deploy to Production Environment'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up JDK ${{ env.JAVA_VERSION }}'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: 'Build application for Production'
        run: ./mvnw -B clean package -Dspring.profiles.active=prod -DskipTests

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './target/seima-server-0.0.1-SNAPSHOT.jar'
          
      - name: 'Post-deployment Notification'
        run: |
          echo "✅ Deployment Successful!"
          echo "🔗 Live URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
