name: 'Deploy to Production'

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Nhập Git tag của phiên bản cần deploy (ví dụ: v1.0.2)'
        required: true
        type: string

env:
  AZURE_WEBAPP_NAME: 'seima-server'
  JAVA_VERSION: '21'
  DISTRIBUTION: 'temurin'

jobs:
  deploy:
    name: 'Deploy to Production Environment'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net

    steps:
      - name: 'Checkout code from tag: ${{ github.event.inputs.version_tag }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version_tag }}

      - name: 'Set up JDK ${{ env.JAVA_VERSION }}'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: 'Build application for Production'
        run: ./mvnw -B clean package -Dspring.profiles.active=prod -DskipTests

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './target/*.jar'
          
      - name: 'Post-deployment Notification'
        run: |
          echo "✅ Deployment Successful!"
          echo "🚀 Version ${{ github.event.inputs.version_tag }} has been deployed to Production."
          echo "🔗 Live URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"