name: 'Dev Integration Build'

on:
  push:
    branches:
      - dev

jobs:
  build-and-publish:
    name: 'Build and Publish Dev Artifact'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Build Application'
        run: ./mvnw -B clean package -DskipTests
      - name: 'Upload Dev Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: dev-build-artifact
          path: ./target/*.jar
          retention-days: 7 # Chỉ lưu bản build của dev trong 7 ngày