name: 'PR Validation Gate'

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    name: 'Build & Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up JDK 21'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 'Build and run tests'
        run: ./mvnw -B clean package

  security-scan:
    name: 'Security Scan'
    runs-on: ubuntu-latest
    if: github.base_ref == 'dev'
    
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Initialize CodeQL'
        uses: github/codeql-action/init@v3
        with:
          languages: java
          # config-file: ./.github/codeql/codeql-config.yml

      # --- THAY ĐỔI Ở ĐÂY ---
      # Thay thế bước 'Autobuild' bằng lệnh build thủ công
      # Điều này đảm bảo CodeQL build code theo đúng cách dự án của bạn được thiết lập
      - name: 'Build the project'
        run: ./mvnw -B clean package -DskipTests
      # ----------------------

      - name: 'Perform CodeQL Analysis'
        uses: github/codeql-action/analyze@v3